### ISSUE TITLE
Dependency Pod::Toc does not exist

### ISSUE THREAD

**Issue by gflohr** [briandfoy/pod-perldoc-totoc#1]
```
$ cpanm Pod::Perldoc::ToToc
--> Working on Pod::Perldoc::ToToc
Fetching http://www.cpan.org/authors/id/B/BD/BDFOY/Pod-Perldoc-ToToc-1.121.tar.gz ... OK
Configuring Pod-Perldoc-ToToc-1.121 ... OK
==> Found dependencies: Pod::Toc
! Finding Pod::Toc on cpanmetadb failed.
! Finding Pod::Toc (0) on mirror http://www.cpan.org failed.
! Couldn't find module or a distribution Pod::Toc
! Installing the dependencies failed: Module 'Pod::Toc' is not installed
! Bailing out the installation for Pod-Perldoc-ToToc-1.121.
```

**Comment by briandfoy** [comment]
Thanks for the report, and congrats on issue #1! 

I've just uploaded 1.122. Let me know how that works out. (It works for me when I install with _cpanm_).

There were two issues:

* It's Pod::TOC, all uppercase
* The module comes with the dist, so it's not a prerequisite

**Comment by briandfoy** [comment]
If you continue to have a problem, just reopen this issues. Thanks,

**Comment by gflohr** [comment]
Works now. Thanks for your quick reaction and apologies for my slow one.
